using M4Graphs.Core.General;

namespace M4Graphs.Core.ModelElements
{
    /// <summary>
    /// Represents an element generated by a <see cref="Model"/>.
    /// </summary>
    public interface IModelElement
    {
        /// <summary>
        /// The element's identifier.
        /// </summary>
        string Id { get; }
        /// <summary>
        /// The element's text.
        /// </summary>
        string Text { get; }
        /// <summary>
        /// The element's generated position.
        /// </summary>
        GeneratedPosition Position { get; }
        /// <summary>
        /// Sets the element's generated position.
        /// </summary>
        /// <param name="x"></param>
        /// <param name="y"></param>
        void SetPosition(int x, int y);
        /// <summary>
        /// A value indicating whether the element has a child element associated with it.
        /// </summary>
        bool HasChild { get; }
    }
}
